---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: todo
  labels:
    app: frontend
    tier: frontend
spec:
  type: LoadBalancer  # ou NodePort si LoadBalancer pas disponible
  selector:
    app: frontend
    tier: frontend
  ports:
  - name: http
    port: 80              # Port externe
    targetPort: 3000      # Port du container
    protocol: TCP